# Generated by Django 5.0.3 on 2024-03-18 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LoginApp", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useractivitylog",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="useractivitylog",
            name="login_in_time",
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="useractivitylog",
            name="logout_time",
            field=models.TimeField(auto_now_add=True),
        ),
    ]
