# Generated by Django 5.0.3 on 2024-03-18 10:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("LoginApp", "0004_alter_useractivitylog_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="useractivitylog",
            old_name="user_id",
            new_name="user_name",
        ),
    ]
