# Generated by Django 5.0.3 on 2024-03-18 12:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("LoginApp", "0005_rename_user_id_useractivitylog_user_name"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserActivityLog",
        ),
    ]
