# Generated by Django 5.0.3 on 2024-03-19 07:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("LoginApp", "0006_delete_useractivitylog"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("product_id", models.AutoField(primary_key=True, serialize=False)),
                ("product_name", models.CharField(max_length=50)),
                ("product_price", models.IntegerField()),
                ("product_image", models.ImageField(upload_to="images/")),
                ("product_description", models.CharField(max_length=1000)),
                ("product_category", models.CharField(max_length=30)),
            ],
        ),
    ]
